---
name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm run ci

      - name: check version
        run: |
          previous_version=$(npm show . version || echo "0.0.0")
          current_version=$(node -p "require('./package.json').version")

          if [ "$current_version" > "$previous_version" ]; then
            echo -e "[+] current version[$current_version] is greater than previous version[$previous_version]"
            echo -e "[+] publishing package to npm registry"

            echo "publish=true" >> $GITHUB_ENV
          else
            echo -e "[-] current version[$current_version] is not greater than previous version[$previous_version]"
            echo -e "[-] skipping publishing package to npm registry"

            echo "publish=false" >> $GITHUB_ENV
          fi

      - name: publish
        if: env.publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
